services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: netflix
    volumes:
      - ../DDL.sql:/docker-entrypoint-initdb.d/01_DDL.sql
      - ../DML.sql:/docker-entrypoint-initdb.d/02_DML.sql
    ports:
      - "5432:5432"
